Delivery/Areas/Admin/Controllers/ExtrasController.cs
using Delivery.Core.Contracts;
using Delivery.Core.ViewModels.Extras;
using Delivery.Infrastructure.Constants;
using Microsoft.AspNetCore.Mvc;

namespace Delivery.Areas.Admin.Controllers
{
    public class ExtrasController : AdministratorController
    {
        private const string Extras = "Добавки";
        private readonly IExtrasService extrasService;
        private readonly ILogger<ExtrasController> logger;

        public ExtrasController(
            IExtrasService extrasService,
            ILogger<ExtrasController> logger)
        {
            this.extrasService = extrasService;
            this.logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                ViewData[GlobalConstants.viewDataTitle] = Extras;
                var model = await extrasService.AllAsync();
                return View(model);
            }
            catch (ArgumentException ae)
            {
                return BadRequest(ae.Message);
            }
        }

        public IActionResult Create()
        {
            ViewData[GlobalConstants.viewDataTitle] = Extras;
            var model = new ExtraInpitModel();
            return View(model);

        }

        [HttpPost]
        public async Task<IActionResult> Create(ExtraInpitModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewData[GlobalConstants.viewDataTitle] = Extras;
                return View(model);
            }

            try
            {
                await extrasService.AddExtraAsync(model);
                return RedirectToAction(nameof(Index));
            }
            catch (ArgumentException ae)
            {
                return BadRequest(ae.Message);
            }
        }


        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                ViewData[GlobalConstants.viewDataTitle] = Extras;
                ExtraEditModel model = await extrasService.GetEditModelAsync(id);
                return View(model);
            }
            catch (ArgumentException ae)
            {
                return BadRequest(ae.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ExtraEditModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewData[GlobalConstants.viewDataTitle] = Extras;
                return View(model);
            }

            try
            {
                await extrasService.UpdateExtraAsync(model);
                return RedirectToAction(nameof(Index));
            }
            catch (ArgumentException ae)
            {
                return BadRequest(ae.Message);
            }
        }


        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await extrasService.DeleteAsync(id);
                return RedirectToAction(nameof(Index));
            }
            catch (ArgumentException ae)
            {
                return BadRequest(ae.Message);
            }
        }
    }
}

Delivery/Areas/Admin/Controllers/PackageController.cs
using Delivery.Core.Contracts;
using Delivery.Core.ViewModels.Packagies;
using Microsoft.AspNetCore.Mvc;

namespace Delivery.Areas.Admin.Controllers
{
    public class PackageController : AdministratorController
    {
        private readonly IPackagesService packageService;

        public PackageController(IPackagesService packageService)
        {
            this.packageService = packageService;
        }

        public async Task<IActionResult> Index()
        {
            List<PackageViewModel> categories = await packageService.GetPackagesWhitoutDeletedAsync();
            return View(categories);
        }

        public IActionResult Create()
        {
            PackageInputModel model = new();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(PackageInputModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await packageService.CreatePackageAsync(model);
                return RedirectToAction(nameof(Index));
            }
            catch (ArgumentException ae)
            {
                return BadRequest(ae.Message);
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                PackageEditModel model = await packageService.GetPackageEditModelAsync(id);

                return View(model);
            }
            catch (ArgumentException ae)
            {
                return BadRequest(ae.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(PackageEditModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await packageService.UpdatePackageAsync(model);
                return RedirectToAction(nameof(Index));
            }
            catch (ArgumentException ae)
            {
                return BadRequest(ae.Message);
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await packageService.DeletePackageAsync(id);

                return RedirectToAction(nameof(Index));
            }
            catch (ArgumentException ae)
            {
                return BadRequest(ae.Message);
            }
        }
    }
}

Delivery/Areas/Guest/Controllers/MenuController.cs
using Delivery.Core.Contracts;
using Delivery.Core.ViewModels.Menu;
using Delivery.Core.ViewModels.Products;
using Delivery.Infrastructure.Constants;
using Microsoft.AspNetCore.Mvc;

namespace Delivery.Areas.Guest.Controllers
{
    [Area(GlobalConstants.AreaGuest)]
    public class MenuController : Controller
    {
        private const string Menu = "Меню";
        private readonly IMenuService menuService;

        public MenuController(IMenuService menuService)
        {
            this.menuService = menuService;
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                ViewData[GlobalConstants.viewDataTitle] = Menu;

                MenuViewModel model = await menuService.GetCategoriesWithProdutsAsync();

                return View(model);
            }
            catch (Exception)
            {

                throw;
            }
        }

        public async Task<IActionResult> GetProductsByCategory(string categoryId)
        {
            try
            {
                ViewData[GlobalConstants.viewDataTitle] = Menu;

                MenuViewModel model = await menuService.GetCategoriesWithProdutsAsync(categoryId);

                ViewData[GlobalConstants.viewDataTitle] = model.Categories.Where(x => x.Id == categoryId).First().Name;

                return View(viewName: nameof(Index), model: model);
            }
            catch (Exception)
            {

                throw;
            }
        }

        public async Task<IActionResult> ShowProduct(string productId)
        {
            try
            {
                ProductDetailsViewModel model = await menuService.GetProductDetailsAsync(productId);

                ViewData[GlobalConstants.viewDataTitle] = Menu;

                return View(model);
            }
            catch (Exception)
            {

                throw;
            }
        }
    }
}

Delivery/Areas/Guest/Controllers/OrdersController.cs
using Delivery.Core.Contracts;
using Delivery.Core.ViewModels.Orders;
using Delivery.Core.ViewModels.ShoppingCart;
using Delivery.Hubs;
using Delivery.Infrastructure.Constants;
using Delivery.Infrastructure.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;

namespace Delivery.Areas.Guest.Controllers
{
    [Area("Guest")]
    public class OrdersController : Controller
    {
        private readonly IAddresesService addresesService;
        private readonly IOrdersService ordersService;
        private readonly UserManager<DeliveryUser> userManager;
        private readonly IHubContext<OrderHub> hubAdmin;
        private readonly SignInManager<DeliveryUser> signInManager;

        public OrdersController(IAddresesService addresesService,
            IOrdersService ordersService,
            UserManager<DeliveryUser> userManager,
            IHubContext<OrderHub> hubAdmin,
            SignInManager<DeliveryUser> signInManager)
        {
            this.addresesService = addresesService;
            this.ordersService = ordersService;
            this.userManager = userManager;
            this.hubAdmin = hubAdmin;
            this.signInManager = signInManager;
        }

        [Authorize(GlobalConstants.AdministratorName)]
        public async Task<IActionResult> Index()
        {
            List<OrderViewModel> orders = await ordersService.GetDailyOrdersAsync();
            return this.View(orders);
        }

        public IActionResult Create()
        {
            var model = new OrderInputModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderInputModel model)
        {
            if (!ModelState.IsValid)
            {
                Response.StatusCode = 418;
                var errors = ModelState.Values.SelectMany(x => x.Errors).Select(s => s.ErrorMessage);
                return Json(errors);
            }

            if (!await ordersService.ValidateWithMirrorObjectAsync(model))
            {
                return BadRequest();
            }

            try
            {
                DeliveryUser user = await GetUser(model);

                int orderId = await ordersService.CreateOrderAsync(model, user);
                await hubAdmin.Clients.All.SendAsync("OperatorNewOrder", orderId);
                this.TempData["NewOrder"] = true;
                return this.Ok();
            }
            catch (Exception)
            {
                throw;
            }
        }

        [Authorize(Roles = GlobalConstants.AdministratorName)]
        public async Task<IActionResult> Details(string orderId)
        {
            if (string.IsNullOrEmpty(orderId))
            {
                return this.NotFound();
            }

            try
            {
                OrderDetailsViewModel model = await ordersService.GetDetailsByIdAsync(orderId);
                return this.View(model);
            }
            catch (Exception)
            {
                return this.NotFound();
            }
        }

        public async Task<AddressViewModel> GetAddressFromLocation(string latitude, string longitude)
        {
            if (string.IsNullOrEmpty(latitude) || string.IsNullOrEmpty(longitude))
            {
                return null;
            }

            try
            {
                AddressViewModel model = await addresesService.GetAddressAsync(latitude, longitude);
                return model;
            }
            catch (Exception)
            {
                return null;
            }
        }

        public async Task<IActionResult> UserOrders()
        {
            var user = await this.userManager.GetUserAsync(this.User);
            if (user == null)
            {
                if (this.Request.Cookies.ContainsKey(GlobalConstants.UserIdCookieKey))
                {
                    user = await this.userManager.FindByIdAsync(this.Request.Cookies[GlobalConstants.UserIdCookieKey]);
                }
            }

            try
            {
                IEnumerable<OrderViewModel> model = await this.ordersService.GetMyOrdersAsync(user);
                return this.View(model);
            }
            catch (Exception )
            {
                return this.NotFound();
            }
        }

        public async Task<IActionResult> UserOrderDetails(string orderId)
        {
            if (string.IsNullOrEmpty(orderId))
            {
                return BadRequest();
            }



            try
            {
                if (int.TryParse(orderId, out int id))
                {
                    UserOrderDetailsViewModel model = await ordersService.GetUserDetailsByIdAsync(id);
                    return this.View(model);
                }

                return BadRequest();
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }

        private async Task<DeliveryUser> GetUser(OrderInputModel model)
        {
            DeliveryUser? user = null;

            if (!User.Identity?.IsAuthenticated ?? true)
            {
                if (Request.Cookies.TryGetValue(GlobalConstants.UserIdCookieKey, out string? userId))
                {
                    user = await userManager.FindByIdAsync(userId);
                }
                else if(user is null)
                {
                    user = new DeliveryUser
                    {

                        UserName = model.Username,
                        PhoneNumber = model.Phone,
                        Email = $"{Request.HttpContext.Connection.RemoteIpAddress}.{DateTime.Now:yyyy:MM:dd:HH:mm}@auto.com",
                        CreatedOn = DateTime.Now,
                        EmailConfirmed = true,
                    };

                    _ = await userManager.CreateAsync(user);
                }

                await signInManager.SignInAsync(user, isPersistent: false, authenticationMethod: GlobalConstants.AuthenticationMethodCookie);
            }
            else
            {
                user = await userManager.FindByNameAsync(User.Identity!.Name);
            }

            UpdateCookie(user.Id);
            return user;
        }

        private void UpdateCookie(string id)
        {
            CookieOptions cookieOptions = new()
            {
                HttpOnly = true,
                Expires = DateTime.Now.AddYears(2),
            };

            Response.Cookies.Append(GlobalConstants.UserIdCookieKey, id, cookieOptions);
        }
    }
}

Delivery/Views/Shared/_DeleteMessagePartial.cshtml
<div class="modal fade" id="messageDialog" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Изтриване</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="$('#messageDialog').modal('hide');">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Сигурни ли сте, че искате да изтриете записа?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal" onclick="$('#messageDialog').modal('hide');">Затвори</button>
        <a id="deleteModalActionButton" href="#"  class="btn btn-danger btn-sm">Да</a>
      </div>
    </div>
  </div>
</div>

@section Scripts{

}

Delivery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
     @await RenderSectionAsync("Style", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Delivery</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Guest" asp-controller="Menu" asp-action="Index" >Меню</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Guest" asp-controller="Orders" asp-action="UserOrders" >Моите Поръчки</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Guest" asp-controller="Orders" asp-action="Create" style="font-size:1.5rem;padding:inherit;">🛒</a>
                        </li> 
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
     <partial name="_CookieConsentPartial" />
    <div>
        <main role="main">
            <div class="container" style="background-color: rgba(180,163,147, 0.5);min-height: calc(100vh - 112px);">
            @RenderBody()
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Delivery - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Delivery/Views/Shared/_ListOrdersPartial.cshtml
@model List<Delivery.Core.ViewModels.Orders.OrderViewModel>

@foreach (var item in Model)
{
    if (item.Status == "Unprocessed")
    {
        <li class="btn btn-danger btn-lg order-li" onclick="orderDetails(@item.OrderId)" id="li@(item.OrderId)" style="width:100%; margin-bottom:2px;">
            <h5>
                Поръчка: <strong id="orderId">@item.OrderId</strong>
            </h5>
        </li>
    }
    else if (item.Status == "Processed")
    {
        <li class="btn btn-warning btn-lg" onclick="orderDetails(@item.OrderId)" id="li@(item.OrderId)" style="width:100%; margin-bottom:2px;">
            <h5>
                Поръчка: <strong id="orderId">@item.OrderId</strong>
            </h5>
        </li>
    }
    else if (item.Status == "OnDelivery")
    {
        <li class="btn btn-success btn-lg" onclick="orderDetails(@item.OrderId)" id="li@(item.OrderId)" style="width:100%; margin-bottom:2px;">
            <h5>
                Поръчка: <strong id="orderId">@item.OrderId</strong>
            </h5>
        </li>
    }
    else if (item.Status == "Delivered")
    {
        <li class="btn btn-info btn-lg" onclick="orderDetails(@item.OrderId)" id="li@(item.OrderId)" style="width:100%; margin-bottom:2px;">
            <h5>
                Поръчка: <strong id="orderId">@item.OrderId</strong>
            </h5>
        </li>
    }

}

Delivery/Views/Shared/_ProductCardPartial.cshtml
@model Delivery.Core.ViewModels.Products.ProductMenuViewModel

<a class="btn col-lg-4 col-md-6 mb-4" asp-area="Guest" asp-controller="Menu" asp-action="ShowProduct" asp-route-productId="@Model.Id">
    <div class="card h-100" id="@Model.Name">
        <img class="card-img-top" src="https://res.cloudinary.com/doyj9avxq/image/upload/c_scale,h_280,w_400/v1648386616/@(Model.ImageUrl)" alt="@Model.Name">
        <div class="card-body">
            <h4 class="name-holder text-center"> @Model.Name </h4>
            <div class="h6">@Model.Weight гр.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@Model.Price лв.</div>
        </div>
        <div class="card-footer text-center">
            <div>
                @for (int i = 1; i < 6; i++)
                {
                    if (i <= Model.Rating)
                    {
                        <div class="checked-star"></div>
                    }
                    else
                    {
                        <div class="unchecked-star"></div>
                    }
                }
            </div>
        </div>
    </div>
</a>

Delivery/Views/Shared/_SideNavMenuPartial.cshtml
<div class="flex-shrink-0 p-3 bg-white" style="width: 280px;">
    <a href="/" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
        <svg class="bi me-2" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-5 fw-semibold">Админ панел</span>
    </a>
    <ul class="list-unstyled ps-0">
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed w-100" data-bs-toggle="collapse" data-bs-target="#category-collapse" aria-expanded="false">
                Категорий
            </button>
            <div class="collapse" id="category-collapse" style="">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a asp-area="Admin" asp-controller="Categories" asp-action="Index" class="link-dark rounded">Лист</a></li>
                    <li><a asp-area="Admin" asp-controller="Categories" asp-action="Create" class="link-dark rounded">Създаване</a></li>
                </ul>
            </div>
        </li>
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed w-100" data-bs-toggle="collapse" data-bs-target="#product-collapse" aria-expanded="false">
                Продукти
            </button>
            <div class="collapse" id="product-collapse" style="">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a asp-area="Admin" asp-controller="Products" asp-action="Index" class="link-dark rounded">Лист</a></li>
                    <li><a asp-area="Admin" asp-controller="Products" asp-action="Create" class="link-dark rounded">Създаване</a></li>
                </ul>
            </div>
        </li>
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed w-100" data-bs-toggle="collapse" data-bs-target="#package-collapse" aria-expanded="false">
                Опаковки
            </button>
            <div class="collapse" id="package-collapse" style="">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a asp-area="Admin" asp-controller="Package" asp-action="Index" class="link-dark rounded">Лист</a></li>
                    <li><a asp-area="Admin" asp-controller="Package" asp-action="Create" class="link-dark rounded">Създаване</a></li>
                </ul>
            </div>
        </li>
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed w-100" data-bs-toggle="collapse" data-bs-target="#allergens-collapse" aria-expanded="false">
                Алергени
            </button>
            <div class="collapse" id="allergens-collapse" style="">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a asp-area="Admin" asp-controller="Allergens" asp-action="Index" class="link-dark rounded">Лист</a></li>
                    <li><a asp-area="Admin" asp-controller="Allergens" asp-action="Create" class="link-dark rounded">Създаване</a></li>
                </ul>
            </div>
        </li>
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed w-100" data-bs-toggle="collapse" data-bs-target="#extras-collapse" aria-expanded="false">
                Добавки
            </button>
            <div class="collapse" id="extras-collapse" style="">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a asp-area="Admin" asp-controller="Extras" asp-action="Index" class="link-dark rounded">Лист</a></li>
                    <li><a asp-area="Admin" asp-controller="Extras" asp-action="Create" class="link-dark rounded">Създаване</a></li>
                </ul>
            </div>
        </li>
        <li class="mb-1">
            <a asp-area="Guest" asp-controller="Orders" asp-action="Index" class="btn btn-toggle align-items-center rounded w-100">Поръчки</a>
        </li>
        <li class="border-top my-3"></li>
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
                Account
            </button>
            <div class="collapse" id="account-collapse" style="">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a href="#" class="link-dark rounded">New...</a></li>
                    <li><a href="#" class="link-dark rounded">Profile</a></li>
                    <li><a href="#" class="link-dark rounded">Settings</a></li>
                    <li><a href="#" class="link-dark rounded">Sign out</a></li>
                </ul>
            </div>
        </li>
    </ul>
</div>